apiVersion: v1
kind: Secret
metadata:
  name: basic-creds
type: Opaque
data:
  username: test
  password: test
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-creds
type: Opaque
data:
  secret: test