### Все карточки
GET http://localhost:8081/cards/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MTY4NjU2LCJleHAiOjE3MzQyNTUwNTZ9.fUoaQz3t5Ipko08PSeR5wdIFx6DryQCjptMhuWwyPtY

### Получение карточки по id
GET http://localhost:8081/cards/by_id?card_id=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MTY4NjU2LCJleHAiOjE3MzQyNTUwNTZ9.fUoaQz3t5Ipko08PSeR5wdIFx6DryQCjptMhuWwyPtY

### Добавиление новой карточки
POST http://localhost:8081/cards/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDE2OTAwMiwiZXhwIjoxNzM0MjU1NDAyfQ.BAdxz3YHxBqQ9JPf5yDCMB1Z1cNn4tdLPsxoxoXHPKo

{
  "title": "Ботинки Puma"
}

### Изменение карточки
POST http://localhost:8081/cards/update
Content-Type: application/json

{
  "id": 8,
  "title": "Ботинки 41-50"
}

### Удаление карточки
GET http://localhost:8081/cards/delete?card_id=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDE2OTAwMiwiZXhwIjoxNzM0MjU1NDAyfQ.BAdxz3YHxBqQ9JPf5yDCMB1Z1cNn4tdLPsxoxoXHPKo

### Все продукты
GET http://localhost:8081/products/all

### Продукт по id
GET http://localhost:8081/products/by_id?product_id=18

### Продукт по card_id + sku
GET http://localhost:8081/products/by_card_id_and_sku?card_id=1&sku=1

### Добавление продукта
POST http://localhost:8081/products/new
Content-Type: application/json

{
    "price": 8000.0,
    "size": 44,
    "color": "черный",
    "country": "RU",
    "card_id": 8,
    "sku": 1
}


### Добавление продукта
POST http://localhost:8081/products/edit
Content-Type: application/json

{
    "id": 21,
    "price": 3000.0
}

### Удаление продукта
GET http://localhost:8081/products/delete?product_id=19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0MTY4NjU2LCJleHAiOjE3MzQyNTUwNTZ9.fUoaQz3t5Ipko08PSeR5wdIFx6DryQCjptMhuWwyPtY



### Регистрация
POST http://localhost:8083/register
Content-Type: application/json

{
  "name": "Serger",
  "surname": "Shil",
  "email": "serger.shil@ya.ru",
  "password": "alm123"
}

### Тест
GET http://88.218.66.164/srv/products-service/cards/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDE3MTE0MywiZXhwIjoxNzM0MjU3NTQzfQ.uRJW7lqWT-3AGNj4u59MBlc7-E6Gre8D2slDIrYYRAM

### Авторизация
POST http://88.218.66.164/srv/auth-service/auth
Content-Type: application/json

{
  "email": "nikita.almester@ya.ru",
  "password": "qwerty123"
}

### Профиль пользователя
POST http://localhost:8085/jwt/verify
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMzMzQwOTY3LCJleHAiOjE3MzM0MjczNjd9.K9MEpNQbCXUUvgN-Qn2geidJr_6KwSPAx0JsAtuGtS4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM1MzU0NDc1LCJleHAiOjE3MzU0NDA4NzV9.TNoV7QvKiuSlaKQbOtEUlF3xfCDptlTZZnzBK7mv7tA
### Получить токен (внутренняя апи)
POST http://localhost:8085/jwt/generate_new
Content-Type: application/json
Authorization: YmFzaWM6YXV0aA==

{
  "id": 15,
  "role": "user"
}

### Провалидировать токен (внутренняя апи)
POST http://localhost:8085/jwt/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM1MzU0NDc1LCJleHAiOjE3MzU0NDA4NzV9.TNoV7QvKiuSlaKQbOtEUlF3xfCDptlTZZnzBK7mv7tA"
}

### Test
GET http://localhost:8083/test