### Создание заказа
POST http://localhost:8086/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM1MzU0NDc1LCJleHAiOjE3MzU0NDA4NzV9.TNoV7QvKiuSlaKQbOtEUlF3xfCDptlTZZnzBK7mv7tA

{
  "user_id": 1,
  "total_amount": 250.50,
  "products": [
    {
      "price": 100.25,
      "product_id": 20,
      "card_id": 67890
    },
    {
      "price": 150.25,
      "product_id": 6,
      "card_id": 98765
    }
  ]
}

### Получение заказа
GET http://localhost:8086/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM1MzU0NDc1LCJleHAiOjE3MzU0NDA4NzV9.TNoV7QvKiuSlaKQbOtEUlF3xfCDptlTZZnzBK7mv7tA


### Получение детализированного заказа
GET http://localhost:8086/orders/detailed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM1MzU0NDc1LCJleHAiOjE3MzU0NDA4NzV9.TNoV7QvKiuSlaKQbOtEUlF3xfCDptlTZZnzBK7mv7tA
